--find all Guids fields without index 

SELECT 
     t.[NAME] AS [Table],
	 C.[NAME] AS [Column]
FROM SYS.COLUMNS AS C 
	INNER JOIN SYS.TABLES AS T ON C.OBJECT_ID = T.OBJECT_ID 
WHERE 
      T.is_ms_shipped = 0
     AND (C.[NAME] LIKE '%GUID%' OR C.[NAME] LIKE '%Guid%')
EXCEPT
SELECT 
   OBJECT_NAME(IC.OBJECT_ID) AS [Table],
   c.[NAME] AS [Column]
FROM 
   SYS.INDEX_COLUMNS  AS IC
   INNER JOIN SYS.ALL_COLUMNS AS C ON  IC.OBJECT_ID = c.OBJECT_ID  AND  IC.COLUMN_ID = C.COLUMN_ID
   INNER JOIN SYS.OBJECTS  AS O ON IC.OBJECT_ID = O.OBJECT_ID 
WHERE 
   IC.KEY_ORDINAL = 1
   AND O.IS_MS_SHIPPED = 0
