-- find all foreign keys without index

SELECT 
   OBJECT_NAME(A.PARENT_OBJECT_ID) AS [Table],
   B.[NAME] AS [FK_Column]
FROM 
   SYS.FOREIGN_KEY_COLUMNS AS A
   INNER JOIN SYS.ALL_COLUMNS AS B ON A.PARENT_COLUMN_ID = B.COLUMN_ID AND A.PARENT_OBJECT_ID = B.OBJECT_ID
   INNER JOIN SYS.OBJECTS As C ON B.OBJECT_ID = C.OBJECT_ID
WHERE 
    C.IS_MS_SHIPPED = 0
EXCEPT
SELECT 
   OBJECT_NAME(A.OBJECT_ID),
   B.[NAME]
FROM 
   SYS.INDEX_COLUMNS AS A
   INNER JOIN SYS.ALL_COLUMNS B ON A.OBJECT_ID = B.OBJECT_ID AND A.COLUMN_ID = B.COLUMN_ID
   INNER JOIN SYS.OBJECTS  AS C ON  A.OBJECT_ID = C.OBJECT_ID
WHERE 
   A.KEY_ORDINAL = 1
   AND A.IS_INCLUDED_COLUMN = 0
   AND C.IS_MS_SHIPPED = 0
